# This is the master config file for the IRIS Client Agent.
# All available options will already be in the yaml file in the correct place,
#   but some are commented out if they are optional settings

# Client-Master.py configuration options
Master:

  # API Server, often times the application server too, but not always
  # Default: localhost
  IRIS_API_SERVER: node1

  # Web Application server
  # Default: localhost
  IRIS_APP_SERVER: node2

  # Polling Rate for the runner (in seconds)
  # DEFAULT: 16
  RUNNER_POLLING_RATE: 16

  # Number of Runner threads
  # DEFAULT: 4
  RUNNER_THREAD_COUNT: 4

  # Number of files to check per run (which directories given will be
  #   logical from the server's POV but will seem random to the client)
  # DEFAULT: 8
  RUNNER_FILE_COUNT: 8

  # Config setting to allow for remote commands to be run
  # DEFAULT: False
  ALLOW_REMOTE_COMMANDS: False

# Runner.py configuration options
Runner:

# Creator.py configuration options
Creator:
  # Hashing algorithm used by Creator. Options are MD5, SHA1, SHA224, SHA256, SHA384, and SHA512
  # DEFAULT: MD5
  HASH_ALGORITHM: MD5
