---
smtpserver: smtp.gmail.com
smtpport: 587
sender: "myemailer@example.com"
password: "mypassword"
recipient: "recipient1@example.com, recipient2@example.com"
subject: "IRIS Alert"
message: "This is the default alert message from the IRIS alerting system"
...
